package com.sprint.HydroGeoLoggerBeta;

import com.j256.ormlite.field.DatabaseField;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class WaterSample {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField(index = true)
    String string;
	@DatabaseField
	long millis;
	@DatabaseField
    Date date;
	@DatabaseField
	boolean even;
    @DatabaseField
    String name;//			vchar
    @DatabaseField(index = true)
    String station;		//vchar
    @DatabaseField
    String hole_type_code;//hole_type_code	fk
    @DatabaseField
    String hole_lining_code;//	fk
    @DatabaseField
    String pipes_in_hole_code;//	fk
    @DatabaseField
    String hole_angle_code;//	fk
    @DatabaseField
    String outflow_type_code;//	fk
    @DatabaseField
    String sampling_issues_code;//	fk
    @DatabaseField
    boolean open;//			bool	this is for code 3 (open / closed)
    @DatabaseField
    float latitude;
    @DatabaseField
    float longitude;
    @DatabaseField
    float masl;//
    @DatabaseField// 			float	called Elev in the spreadsheet
    float water_table;//		float
    @DatabaseField
    float sample_depth;		//float
    @DatabaseField
    float bottom_of_hole;//	float
    @DatabaseField
    float temperature;	//	float
    @DatabaseField
    float condition;//		float
    @DatabaseField
    String notes;//			varchar
    @DatabaseField
    float tree_sampled_height;//	float
    @DatabaseField
    float tree_sampled_width;//	float
    @DatabaseField
    float tree_sampled_longitude;

    public float getTree_sampled_latitude() {
        return tree_sampled_latitude;
    }

    public void setTree_sampled_latitude(float tree_sampled_latitude) {
        this.tree_sampled_latitude = tree_sampled_latitude;
    }

    @DatabaseField
    float tree_sampled_latitude;


    WaterSample() {
		// needed by ormlite
	}

	public WaterSample(long millis) {
		this.date = new Date(millis);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("string=").append(string);
		sb.append(", ").append("millis=").append(millis);
		SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=").append(dateFormatter.format(date));
		sb.append(", ").append("even=").append(even);
		return sb.toString();
	}
}
